### ISSUE TITLE
Docker version can't reach https://sts.amazonaws.com/

### ISSUE THREAD

**Issue by mdemers-kronos** [kronostechnologies/kpin#2]
Got this error when running the docker version

`botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://sts.amazonaws.com/"
`

Works on local. Ubuntu 17.10

**Comment by nvanheuverzwijn** [comment]
@mdemers-kronos Can you be more explicit ? What were you trying to do  and what command did you run ?
